---

name: Publish on PyPI

on:
  push:
    tags:
      - "*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1

...
