---

name: Quality Assurance

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      ref:
        description: A git reference to check out.
        default: 1.3.x
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7  # 2023-06-07
          - 3.8  # 2024-10
          - 3.9  # 2025-10
          - pypy3
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
      - run: python -m pip install --upgrade pip setuptools tox
      - run: tox -e py

  CodeQL:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref || github.ref }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'python'
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  other:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: doclinks
          - environment: doctest
          - environment: linting
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
      - run: python -m pip install --upgrade pip setuptools tox
      - run: tox -e ${{ matrix.environment }}

...
