---

name: Quality Assurance
on:
  - pull_request
  - push
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - 2.7
          - pypy2
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - pypy3
        include:
          - os: ubuntu-18.04
            python-version: 3.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip setuptools tox
      - run: tox -e py

  other:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: doclinks
          - environment: doctest
          - environment: linting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip setuptools tox
      - run: tox -e ${{ matrix.environment }}

...
