---

name: Quarterly checks

on:
  schedule:
    - cron: "44 19 16 */3 *"

jobs:

  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'python'
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install tox
      - run: tox -e doclinks

...
